# Generated by Django 5.1.3 on 2024-11-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('street', models.CharField(max_length=100)),
                ('zipcode', models.BigIntegerField()),
                ('state', models.CharField(max_length=2)),
                ('apt_num', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('account_type', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_init', models.CharField(max_length=2)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('number_of_employees', models.BigIntegerField()),
                ('rating', models.CharField(max_length=10)),
                ('owner', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('in_stock', models.IntegerField()),
                ('rating', models.CharField(max_length=10)),
            ],
        ),
    ]
