# Generated by Django 5.1.3 on 2024-11-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bird',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('vaccinated', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=255)),
                ('species', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('breed', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('vaccinated', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('vaccinated', models.BooleanField(default=False)),
                ('breed', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='exotic_animal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('region_of_origin', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('type_of_animal', models.CharField(max_length=255)),
                ('vaccinated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('number_of_pets', models.IntegerField(default=1)),
            ],
        ),
    ]
